// <auto-generated />
using System;
using DroneLogger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneLogger.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007004020_AddFlightTelemetry")]
    partial class AddFlightTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DroneLogger.Api.Domain.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Battery")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightController")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgCurrentA")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgSpeedMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgThrottlePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("BatteryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CellCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorruptFrames")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataVersion")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DistanceM")
                        .HasColumnType("REAL");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EndVoltage")
                        .HasColumnType("REAL");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double?>("HomeLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("HomeLon")
                        .HasColumnType("REAL");

                    b.Property<int>("LogIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MahUsed")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxBaroHeightM")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxDistanceM")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxHeightM")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeedMs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxThrottlePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinRssiPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinVoltage")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PeakCurrentA")
                        .HasColumnType("REAL");

                    b.Property<double?>("PeakPowerW")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartVoltage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SticksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TuneSnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TuneSnapshotId");

                    b.HasIndex("AircraftId", "FileHash");

                    b.HasIndex("AircraftId", "StartedAt");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.TuneSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("TuneSettings");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.TuneSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId", "CreatedAt");

                    b.ToTable("TuneSnapshots");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.Flight", b =>
                {
                    b.HasOne("DroneLogger.Api.Domain.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DroneLogger.Api.Domain.TuneSnapshot", "TuneSnapshot")
                        .WithMany()
                        .HasForeignKey("TuneSnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aircraft");

                    b.Navigation("TuneSnapshot");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.TuneSetting", b =>
                {
                    b.HasOne("DroneLogger.Api.Domain.TuneSnapshot", "Snapshot")
                        .WithMany("Settings")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.TuneSnapshot", b =>
                {
                    b.HasOne("DroneLogger.Api.Domain.Aircraft", "Aircraft")
                        .WithMany("Tunes")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Tunes");
                });

            modelBuilder.Entity("DroneLogger.Api.Domain.TuneSnapshot", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
